apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: simple-kanban
build:
  artifacts:
  - image: simple-kanban
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  helm:
    releases:
    - name: simple-kanban-postgres
      remoteChart: bitnami/postgresql
      version: "16.7.11"
      setValues:
        auth.postgresPassword: kanban
        auth.username: kanban
        auth.password: kanban
        auth.database: simple_kanban
        primary.persistence.size: 8Gi
    - name: simple-kanban-redis
      remoteChart: bitnami/redis
      version: "21.2.3"
      setValues:
        auth.password: kanban
        master.persistence.size: 8Gi
    - name: simple-kanban
      chartPath: helm/simple-kanban
      valuesFiles:
      - helm/simple-kanban/values-dev.yaml
      setValues:
        image.repository: simple-kanban
        image.tag: simple-kanban
portForward:
- resourceType: service
  resourceName: simple-kanban
  port: 8000
  localPort: 8000
- resourceType: service
  resourceName: simple-kanban-postgres
  port: 5432
  localPort: 5432
- resourceType: service
  resourceName: simple-kanban-redis-master
  port: 6379
  localPort: 6379
profiles:
- name: dev
  deploy:
    helm:
      releases:
      - name: simple-kanban-postgres
        remoteChart: bitnami/postgresql
        version: "16.7.11"
        setValues:
          auth.postgresPassword: kanban
          auth.username: kanban
          auth.password: kanban
          auth.database: simple_kanban
          primary.persistence.size: 8Gi
      - name: simple-kanban-redis
        remoteChart: bitnami/redis
        version: "21.2.3"
        setValues:
          auth.password: kanban
          master.persistence.size: 8Gi
      - name: simple-kanban
        chartPath: helm/simple-kanban
        valuesFiles:
        - helm/simple-kanban/values-dev.yaml
- name: prod
  deploy:
    helm:
      releases:
      - name: simple-kanban-postgres
        remoteChart: bitnami/postgresql
        version: "16.7.11"
        setValues:
          auth.postgresPassword: ${POSTGRES_PASSWORD}
          auth.username: kanban
          auth.password: ${POSTGRES_USER_PASSWORD}
          auth.database: simple_kanban
          primary.persistence.size: 100Gi
          metrics.enabled: true
      - name: simple-kanban-redis
        remoteChart: bitnami/redis
        version: "21.2.3"
        setValues:
          auth.password: ${REDIS_PASSWORD}
          master.persistence.size: 20Gi
          metrics.enabled: true
      - name: simple-kanban
        chartPath: helm/simple-kanban
        valuesFiles:
        - helm/simple-kanban/values-prod.yaml
