apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: simple-kanban
build:
  artifacts:
  - image: registry.stormpath.net/simple-kanban
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  helm:
    releases:
    - name: simple-kanban
      chartPath: helm/simple-kanban
      namespace: apps
      valuesFiles:
      - helm/simple-kanban/values-dev.yaml
      setValues:
        image.repository: registry.stormpath.net/simple-kanban
portForward:
- resourceType: service
  resourceName: simple-kanban
  port: 8000
  localPort: 8000
profiles:
- name: dev
  deploy:
    helm:
      releases:
      - name: simple-kanban
        chartPath: helm/simple-kanban
        namespace: apps
        valuesFiles:
        - helm/simple-kanban/values-dev.yaml
        setValues:
          image.repository: registry.stormpath.net/simple-kanban
- name: prod
  deploy:
    helm:
      releases:
      - name: simple-kanban-postgres
        remoteChart: bitnami/postgresql
        version: "16.7.11"
        setValues:
          auth.postgresPassword: ${POSTGRES_PASSWORD}
          auth.username: kanban
          auth.password: ${POSTGRES_USER_PASSWORD}
          auth.database: simple_kanban
          primary.persistence.size: 100Gi
          metrics.enabled: true
      - name: simple-kanban-redis
        remoteChart: bitnami/redis
        version: "21.2.3"
        setValues:
          auth.password: ${REDIS_PASSWORD}
          master.persistence.size: 20Gi
          metrics.enabled: true
      - name: simple-kanban
        chartPath: helm/simple-kanban
        valuesFiles:
        - helm/simple-kanban/values-prod.yaml
