# Default values for simple-kanban
replicaCount: 1

image:
  repository: simple-kanban
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  DATABASE_URL: "postgresql://user:password@postgres:5432/kanban"
  REDIS_URL: "redis://redis:6379/0"
  JWT_SECRET_KEY: "your-secret-key-here"
  SESSION_SECRET_KEY: "your-session-secret-here"
  # OpenTelemetry configuration - OTLP supports both HTTP and gRPC
  OTEL_SERVICE_NAME: "simple-kanban"
  OTEL_SERVICE_VERSION: "1.0.0"
  # HTTP protocol (recommended for simplicity and firewall compatibility)
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://prometheus-gateway:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  # Alternative: gRPC (better performance) - use port 4317 and protocol "grpc"
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "0.1"  # Sample 10% of traces in production

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: simple-kanban.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Health checks
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

# Environment variables
env: []

# ConfigMap data
configMap:
  data: {}

# Secret data
secret:
  data: {}
