groups:
- name: simple-kanban
  rules:
  - alert: HighErrorRate
    expr: rate(http_requests_total{job="simple-kanban",status=~"5.."}[5m]) / rate(http_requests_total{job="simple-kanban"}[5m]) * 100 > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value }}% for the last 5 minutes"

  - alert: HighLatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="simple-kanban"}[5m])) > 0.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response latency detected"
      description: "95th percentile latency is {{ $value }}s"

  - alert: ServiceDown
    expr: up{job="simple-kanban"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Simple Kanban service is down"
      description: "Simple Kanban service has been down for more than 1 minute"

  - alert: DatabaseConnectionIssues
    expr: db_connections_active{job="simple-kanban"} > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High database connection usage"
      description: "Database connections are at {{ $value }}, approaching limit"
